# Generated by Django 5.0.2 on 2024-02-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('САЛАТЫ', 'САЛАТЫ'), ('ЗАКУСКИ', 'ЗАКУСКИ'), ('СУПЫ', 'СУПЫ'), ('ГОРЯЧЕЕ', 'ГОРЯЧЕЕ'), ('ДЕСЕРТЫ', 'ДЕСЕРТЫ')], default='САЛАТЫ', max_length=20)),
                ('slug', models.SlugField(default='salads', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Descriptions')),
                ('slug', models.SlugField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reciple_book.category')),
            ],
        ),
    ]
