# Generated by Django 5.0.2 on 2024-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciple_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('САЛАТЫ', 'САЛАТЫ'), ('ПЕРВЫЕ БЛЮДА', 'ПЕРВЫЕ БЛЮДА'), ('ВТОРЫЕ БЛЮДА', 'ВТОРЫЕ БЛЮДА'), ('ДЕСЕРТЫ', 'ДЕСЕРТЫ')], default='САЛАТЫ', max_length=20),
        ),
    ]
